### PR TITLE
docs: import Casa and Super Gluu docs from Gluu to Gluu Flex

### LINKED ISSUE #1062: docs: Import Casa and Super Gluu documentation into Flex
As per @nynymike's comment in chat  Gluu Casa and Super Gluu documentation should be moved to Flex. This involves

- [ ] Move Casa documentation from [here](https://gluu.org/docs/#gluu-casa)
- [ ] Move Super Gluu documentation from [here](https://gluu.org/docs/#super-gluu)
- [ ] Remove Casa section from [here](https://docs.gluu.org/head/admin/casa/)

Casa and Super Gluu should be two new top level documentation categories as shown in the image below:

Clipboard - May 29, 2023 11_31 AM

### PR DESCRIPTION
**Pull request by ossdhaval**
Following are the tasks involved:

- [x] Move docs to Flex repo
- [x] Update mkdocs navigation
- [x] Move images to `assets` 
- [x] Fix broken links
- [ ] Review and update content where appropriate to align with Flex instead of Gluu Server

Closes #1062

### CODE REVIEW

**Comment by ossdhaval** [comment]
@moabu @jgomer2001 @maduvena 

Docs have been physically migrated and working from new location with this PR. I have left old docs in Gluu server untouched.

Content must be reviewed closely to ensure it aligns with Gluu Flex and not Gluu Server. Things like
- `Gluu Server` text should be replaced by `Gluu Flex Server`
- Does Flex refer to `oxAuth` as `Janssen Auth Server`? If so, then that also needs to be replaced. And other similar replacements.
- There might be other required updates to the content as well. 
Can @jgomer2001 or @maduvena review the entire content, and update it where necessary in this PR?

**Comment by jgomer2001** [comment]
This means the content was only transferred and not fixed?

**Comment by jgomer2001** [comment]
@ossdhaval I wiped content that does not exist anymore or we cannot maintain, and added some fixes

This is regarding casa ofc - I don't know who is in charge of updating SG docs

The following need total rewrite, please do if possible:

docs/casa/administration/installation.md
docs/casa/administration/uninstallation.md
docs/casa/quick-start.md
docs/casa/plugins/bioid.md (@maduvena can help - or remove if we don't offer this plugin)

**Comment by ossdhaval** [comment]
In that case, let me comment out navigation to bioID docs.

**Comment by ossdhaval** [comment]
@mzico has enlisted to review and fix Super Gluu documents. Thanks Zico.

**Review by jgomer2001 — DISMISSED** [review]

**Review by jgomer2001 — CHANGES_REQUESTED** [review]
we are not supporting stytch. Actually the only casa-flex plugin using external technologies should be bioid. I am sure I removed all files and references to those unmaintained plugins - I dont recall if this was pushed to main branch or this one...

**Comment by ossdhaval** [comment]
@jgomer2001 I think it was [this commit](https://github.com/GluuFederation/flex/commit/d8d63819d799c7d546b8770834d76c9e98a4c32a).

**Review by jgomer2001 — DISMISSED** [review]

**Review by jgomer2001 — APPROVED** [review]

**Pull request merged**
